
services:

  lab_db:
    image: postgres:15-alpine
    container_name: lab_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
    volumes:
      - lab_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://lab_db:5432/${POSTGRES_DB:-appdb}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-appuser}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS:-http://localhost}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      lab_db:
        condition: service_healthy
    healthcheck:
      disable: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      BASE_URL: ${BASE_URL}
      API_BASE_URL: ${API_BASE_URL}
      API_BASE_PORT: ${API_BASE_PORT}
      GRAPHQL_END_POINT: ${GRAPHQL_END_POINT}
      API_REST_END_POINT: ${API_REST_END_POINT}
    depends_on:
      - backend
    healthcheck:
      disable: true
    ports:
      - "443:443"
    volumes:
      # Certificats Let's Encrypt (lecture seule dans nginx)
      - certbot_certs:/etc/letsencrypt:ro


volumes:
  lab_db_data:
  certbot_certs:
